/* ####################################################################### *\
|| #           PONTO DE ENTRADA UTILIZADO PELO IMPORTADOR GATI           # ||
|| #                                                                     # ||
|| #    PONTO DE ENTRADA UTILIZADO PARA INSERIR NOVAS OPÇÕES NO ARRAY    # ||
|| #                   AROTINA EM DOCUMENTO DE ENTRADA                   # ||
\* ####################################################################### */

User Function GMTA103MNU()
	U_GTPE010()
Return